FROM python:3.11-alpine

ENV BASE_DIR=/usr/src/app
WORKDIR $BASE_DIR
RUN mkdir -p $WORKDIR/static
RUN mkdir -p $WORKDIR/media

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# add bash
RUN apk add --no-cache bash

# install pip
RUN set -xe \
    && apk update \
    && apk add py3-pip

# copy project
# TODO: exclude static files
COPY ./config/ $BASE_DIR/config/
COPY ./nsign/ $BASE_DIR/nsign/
COPY ./requirements/ $BASE_DIR/requirements/
COPY ./manage.py $BASE_DIR

# install dependencies
RUN pip install --upgrade pip
RUN pip install -r $BASE_DIR/requirements/base.txt
