# Generated by Django 4.2 on 2023-04-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='is_delete',
        ),
        migrations.AlterField(
            model_name='version',
            name='version',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Version'),
        ),
    ]
